import { useEffect, useMemo, useState, type CSSProperties, type FormEvent } from "react";
import { AlertCircle, CheckCircle2, ChevronDown, Database, Download, Filter, LoaderCircle, LogIn, LogOut, PieChart, RefreshCw, Search, ServerCog, ShieldCheck, Trash2, UserPlus, X } from "lucide-react";
import { CATEGORY_LABELS, CATEGORY_OPTIONS, ROLE_LABELS, ROLE_OPTIONS, categoryShortLabel } from "@/lib/user-form";
import { normalizePhone } from "@/lib/phone";
import { clearSupabaseConnection, configureSupabase, deleteUser, getAdminContext, getSupabaseConnection, isSupabaseConfigured, loadUsers, signInAdmin, signOutAdmin, testSupabaseConnection, updateUser, type UserCategory, type UserRecord, type UserRole } from "@/lib/supabase";

type Props = { onConnectionChanged: () => void; onRequestCreate: () => void };
type Notice = { kind: "error" | "success"; message: string } | null;
type EditDraft = Pick<UserRecord, "id" | "full_name" | "phone" | "role" | "user_category" | "supervisor_id" | "permanent_shop_id">;
type CustomSelectProps = { value: string; options: Array<{ value: string; label: string }>; placeholder: string; onChange: (value: string) => void; ariaLabel: string };

function CustomSelect({ value, options, placeholder, onChange, ariaLabel }: CustomSelectProps) {
  const [open, setOpen] = useState(false);
  const current = options.find((option) => option.value === value)?.label || placeholder;
  return <div className={`custom-select ${open ? "is-open" : ""}`}><button type="button" className="custom-select-trigger" aria-label={ariaLabel} aria-expanded={open} onClick={() => setOpen((state) => !state)}><span>{current}</span><ChevronDown className="select-chevron" size={14} strokeWidth={1.8} /></button>{open && <><button className="select-backdrop" type="button" aria-label="Fermer" onClick={() => setOpen(false)} /><div className="custom-select-menu">{options.map((option) => <button type="button" className={option.value === value ? "is-selected" : ""} key={option.value} onClick={() => { onChange(option.value); setOpen(false); }}>{option.label}{option.value === value && <CheckCircle2 size={13} />}</button>)}</div></>}</div>;
}
function escapeCsv(value: unknown): string { return `"${String(value ?? "").replaceAll('"', '""')}"`; }

function AdminDashboard({ onConnectionChanged, onRequestCreate }: Props) {
  const [configured, setConfigured] = useState(isSupabaseConfigured());
  const [profile, setProfile] = useState<UserRecord | null>(null);
  const [users, setUsers] = useState<UserRecord[]>([]);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState("");
  const [roleFilter, setRoleFilter] = useState("all");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [showConfig, setShowConfig] = useState(!configured);
  const [setupUrl, setSetupUrl] = useState(getSupabaseConnection()?.url || "");
  const [setupKey, setSetupKey] = useState("");
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [notice, setNotice] = useState<Notice>(null);
  const [connectionTest, setConnectionTest] = useState<Notice>(null);
  const [testingConnection, setTestingConnection] = useState(false);
  const [editDraft, setEditDraft] = useState<EditDraft | null>(null);
  const [deleteCandidate, setDeleteCandidate] = useState<UserRecord | null>(null);
  const [actionLoading, setActionLoading] = useState(false);
  const isAuthenticated = Boolean(profile);
  const canManage = profile?.role === "admin" || profile?.role === "super_admin";
  const isReadOnly = Boolean(profile && !canManage);

  async function refreshSession() { if (!isSupabaseConfigured()) return; try { const current = await getAdminContext(); setProfile(current?.profile || null); if (current) await refreshUsers(); } catch (error) { setProfile(null); setNotice({ kind: "error", message: error instanceof Error ? error.message : "Session indisponible." }); } }
  async function refreshUsers() { setLoading(true); try { setUsers(await loadUsers()); setNotice(null); } catch { setNotice({ kind: "error", message: "Impossible de charger public.users. Vérifiez les politiques RLS." }); } finally { setLoading(false); } }
  useEffect(() => { void refreshSession(); }, []);
  async function handleSetup(event: FormEvent) { event.preventDefault(); try { configureSupabase(setupUrl, setupKey); setConfigured(true); setSetupKey(""); setShowConfig(false); setConnectionTest(null); setNotice({ kind: "success", message: "Supabase est configuré." }); onConnectionChanged(); await refreshSession(); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "Configuration Supabase invalide." }); } }
  async function handleTestConnection() { setTestingConnection(true); setConnectionTest(null); try { await testSupabaseConnection(setupUrl, setupKey); setConnectionTest({ kind: "success", message: "Connexion valide." }); } catch (error) { setConnectionTest({ kind: "error", message: error instanceof Error ? error.message : "Connexion impossible." }); } finally { setTestingConnection(false); } }
  async function handleLogin(event: FormEvent) { event.preventDefault(); setLoading(true); try { const current = await signInAdmin(phone, password); setProfile(current.profile); setPhone(""); setPassword(""); await refreshUsers(); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "MSISDN ou mot de passe incorrect." }); } finally { setLoading(false); } }
  async function handleLogout() { await signOutAdmin(); setProfile(null); setUsers([]); }
  function handleDisconnect() { clearSupabaseConnection(); setConfigured(false); setProfile(null); setUsers([]); setShowConfig(true); setSetupKey(""); onConnectionChanged(); }
  const filteredUsers = useMemo(() => { const query = search.trim().toLowerCase(); const normalizedQuery = normalizePhone(search); return users.filter((user) => (!query || user.full_name.toLowerCase().includes(query) || user.phone.includes(normalizedQuery) || user.phone.includes(query)) && (roleFilter === "all" || user.role === roleFilter) && (categoryFilter === "all" || user.user_category === categoryFilter)); }, [users, search, roleFilter, categoryFilter]);
  const categoryStats = useMemo(() => CATEGORY_OPTIONS.map((category) => ({ category, count: users.filter((user) => user.user_category === category).length })).filter((item) => item.count > 0), [users]);
  const donutGradient = useMemo(() => { const colors = ["#9ee9e8", "#b5ef8c", "#d3b5ff", "#ffca8a"]; const total = Math.max(users.length, 1); let cursor = 0; return `conic-gradient(${categoryStats.length ? categoryStats.map((item, index) => { const start = cursor; cursor += (item.count / total) * 100; return `${colors[index % colors.length]} ${start}% ${cursor}%`; }).join(", ") : "#29444b 0 100%"})`; }, [categoryStats, users.length]);
  function exportCsv() { const headers = ["id", "full_name", "phone", "role", "user_category", "supervisor_id", "permanent_shop_id"]; const rows = filteredUsers.map((user) => [user.id, user.full_name, user.phone, user.role, user.user_category || "", user.supervisor_id || "", user.permanent_shop_id || ""].map(escapeCsv).join(",")); const blob = new Blob([[headers.join(","), ...rows].join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `btl-users-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url); }
  function beginEdit(user: UserRecord) { if (!canManage) return; setEditDraft({ id: user.id, full_name: user.full_name, phone: user.phone, role: user.role, user_category: user.user_category, supervisor_id: user.supervisor_id, permanent_shop_id: user.permanent_shop_id }); }
  async function saveEdit(event: FormEvent) { event.preventDefault(); if (!editDraft) return; setActionLoading(true); try { const updated = await updateUser(editDraft.id, { full_name: editDraft.full_name.trim(), phone: normalizePhone(editDraft.phone), role: editDraft.role, user_category: editDraft.user_category, supervisor_id: editDraft.supervisor_id || null, permanent_shop_id: editDraft.permanent_shop_id || null }); setUsers((current) => current.map((user) => user.id === updated.id ? updated : user)); setEditDraft(null); setNotice({ kind: "success", message: `${updated.full_name} a été mis à jour.` }); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "Modification impossible." }); } finally { setActionLoading(false); } }
  async function confirmDelete() { if (!deleteCandidate) return; setActionLoading(true); try { await deleteUser(deleteCandidate.id); setUsers((current) => current.filter((user) => user.id !== deleteCandidate.id)); setNotice({ kind: "success", message: `${deleteCandidate.full_name} a été supprimé.` }); setDeleteCandidate(null); } catch (error) { setNotice({ kind: "error", message: error instanceof Error ? error.message : "Suppression impossible." }); } finally { setActionLoading(false); } }

  return <section className="admin-dashboard glass-card">
    <div className="dashboard-header"><div className="dashboard-title"><div className="heading-icon"><ServerCog size={19} /></div><div><div className="eyebrow"><ShieldCheck size={13} /> Console sécurisée</div><h2>Tableau de bord administrateur</h2></div></div><div className="dashboard-actions">{profile && <span className="session-chip"><span className="session-dot" />{profile.full_name} · {ROLE_LABELS[profile.role]}</span>}{profile && <button className="icon-button" type="button" onClick={() => void handleLogout()} aria-label="Se déconnecter" title="Se déconnecter"><LogOut size={15} /></button>}{profile?.role === "super_admin" && <button className="icon-button primary-icon" type="button" onClick={onRequestCreate} aria-label="Nouvel utilisateur" title="Nouvel utilisateur"><UserPlus size={16} /></button>}{configured && <button className="icon-button" type="button" onClick={() => setShowConfig(true)} aria-label="Configurer la base de données" title="Configurer la base de données"><Database size={16} /></button>}</div></div>
    {notice && <div className={`dashboard-notice ${notice.kind}`}><span>{notice.kind === "success" ? <CheckCircle2 size={15} /> : <AlertCircle size={15} />}</span>{notice.message}<button type="button" onClick={() => setNotice(null)} aria-label="Fermer"><X size={14} /></button></div>}
    {!configured && !showConfig && <div className="dashboard-empty"><ServerCog size={27} /><strong>Connectez votre projet Supabase</strong><button className="button primary compact" type="button" onClick={() => setShowConfig(true)}><Database size={14} /> Configurer</button></div>}
    {configured && !isAuthenticated && !showConfig && <form className="admin-login" onSubmit={handleLogin}><div className="login-icon"><LogIn size={19} /></div><div className="login-copy"><strong>Connexion par MSISDN requise</strong><span>Les données réelles sont verrouillées jusqu’à l’identification dans public.users.</span></div><input value={phone} onChange={(event) => setPhone(event.target.value)} type="tel" placeholder="081 234 5678" aria-label="MSISDN de connexion" inputMode="tel" required /><input value={password} onChange={(event) => setPassword(event.target.value)} type="password" placeholder="Mot de passe" aria-label="Mot de passe" required /><button className="button primary compact" type="submit" disabled={loading}>{loading ? <LoaderCircle className="spin" size={14} /> : <LogIn size={14} />} Se connecter</button></form>}
    {configured && isAuthenticated && <>{isReadOnly && <div className="readonly-banner"><ShieldCheck size={15} /><span><strong>Lecture seule</strong> · {ROLE_LABELS[profile!.role]}</span></div>}
      <div className="dashboard-toolbar"><div className="history-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher un MSISDN ou un nom…" aria-label="Rechercher dans l’historique" /></div><div className="filter-control"><Filter size={14} /><CustomSelect value={roleFilter} onChange={setRoleFilter} ariaLabel="Filtrer par rôle" placeholder="Tous les rôles" options={[{ value: "all", label: "Tous les rôles" }, ...ROLE_OPTIONS.map((role) => ({ value: role, label: ROLE_LABELS[role] }))]} /></div><div className="filter-control"><CustomSelect value={categoryFilter} onChange={setCategoryFilter} ariaLabel="Filtrer par catégorie" placeholder="Toutes les catégories" options={[{ value: "all", label: "Toutes les catégories" }, ...CATEGORY_OPTIONS.map((category) => ({ value: category, label: categoryShortLabel(category) }))]} /></div><button className="icon-button" type="button" onClick={() => void refreshUsers()} disabled={loading} aria-label="Actualiser" title="Actualiser">{loading ? <LoaderCircle className="spin" size={15} /> : <RefreshCw size={15} />}</button><button className="icon-button primary-icon" type="button" onClick={exportCsv} disabled={!filteredUsers.length} aria-label="Exporter CSV" title="Exporter CSV"><Download size={15} /></button></div>
      <div className="dashboard-stats"><span><strong>{filteredUsers.length}</strong> résultat{filteredUsers.length > 1 ? "s" : ""}</span><span><strong>{users.length}</strong> utilisateur{users.length > 1 ? "s" : ""}</span><span className="secure-label"><ShieldCheck size={13} /> Sans password_hash</span></div>
      <div className="dashboard-insights"><div className="donut-card"><div className="donut-heading"><span><PieChart size={14} /> Répartition campagne</span><small>{users.length} total</small></div><div className="donut-content"><div className="donut" style={{ "--donut": donutGradient } as CSSProperties}><div><strong>{users.length}</strong><small>profils</small></div></div><div className="donut-legend">{categoryStats.length ? categoryStats.map((item, index) => <div key={item.category}><i style={{ background: ["#9ee9e8", "#b5ef8c", "#d3b5ff", "#ffca8a"][index % 4] }} /> <span>{categoryShortLabel(item.category)}</span><b>{item.count}</b></div>) : <span className="muted-note">Aucune catégorie renseignée</span>}</div></div></div><div className="role-summary"><div className="donut-heading"><span><ShieldCheck size={14} /> Rôles actifs</span><small>{users.length} profils</small></div>{ROLE_OPTIONS.map((role) => { const count = users.filter((user) => user.role === role).length; return count ? <div className="role-line" key={role}><span>{ROLE_LABELS[role]}</span><b>{count}</b><div><i style={{ width: `${Math.max(8, (count / Math.max(users.length, 1)) * 100)}%` }} /></div></div> : null; })}</div></div>
      <div className="users-table-wrap"><table className="users-table"><thead><tr><th>Utilisateur</th><th>MSISDN</th><th>Rôle</th><th>Catégorie</th><th>Superviseur</th><th>Shop</th>{canManage && <th aria-label="Actions" />}</tr></thead><tbody>{filteredUsers.map((user) => <tr key={user.id} className={canManage ? "row-clickable" : ""} onClick={() => beginEdit(user)}><td><div className="table-user"><div className="avatar small">{user.full_name.slice(0, 1).toUpperCase()}</div><div><strong>{user.full_name}</strong><small>{user.id}</small></div></div></td><td><span className="mono-value">{user.phone}</span></td><td><span className={`role-badge role-${user.role}`}>{ROLE_LABELS[user.role]}</span></td><td>{user.user_category ? CATEGORY_LABELS[user.user_category].split(" — ")[0] : "—"}</td><td>{user.supervisor_id ? <span className="mono-value">{user.supervisor_id.slice(0, 8)}…</span> : "—"}</td><td>{user.permanent_shop_id || "—"}</td>{canManage && <td><button type="button" className="icon-action delete" aria-label={`Supprimer ${user.full_name}`} title="Supprimer" onClick={(event) => { event.stopPropagation(); setDeleteCandidate(user); }}><Trash2 size={14} /></button></td>}</tr>)}</tbody></table>{!filteredUsers.length && <div className="table-empty"><Search size={22} /><strong>Aucun utilisateur trouvé</strong><span>Essayez un MSISDN ou élargissez vos filtres.</span></div>}</div>
    </>}
    {showConfig && <div className="modal-layer"><button className="modal-backdrop" type="button" aria-label="Fermer" onClick={() => configured && setShowConfig(false)} /><form className="modal-card config-modal" onSubmit={handleSetup}><div className="modal-header"><div><div className="eyebrow"><Database size={13} /> Connexion</div><h3>Base Supabase</h3></div>{configured && <button type="button" className="modal-close" onClick={() => setShowConfig(false)} aria-label="Fermer"><X size={16} /></button>}</div><label>URL du projet<input value={setupUrl} onChange={(event) => setSetupUrl(event.target.value)} placeholder="https://votre-projet.supabase.co" required /></label><label>Clé publishable<input value={setupKey} onChange={(event) => setSetupKey(event.target.value)} placeholder="Clé publishable / anon" type="password" autoComplete="off" required /></label>{connectionTest && <div className={`connection-test ${connectionTest.kind}`}><span>{connectionTest.kind === "success" ? <CheckCircle2 size={14} /> : <AlertCircle size={14} />}</span>{connectionTest.message}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={() => void handleTestConnection()} disabled={testingConnection}>{testingConnection ? <LoaderCircle className="spin" size={14} /> : <Database size={14} />} Tester</button><button type="submit" className="button primary" disabled={testingConnection}><CheckCircle2 size={14} /> Enregistrer</button></div>{configured && <button type="button" className="text-button danger config-disconnect" onClick={handleDisconnect}>Déconnecter ce projet</button>}</form></div>}
    {deleteCandidate && <div className="modal-layer"><button className="modal-backdrop" type="button" aria-label="Fermer" onClick={() => setDeleteCandidate(null)} /><div className="modal-card confirm-card"><div className="danger-icon"><Trash2 size={19} /></div><h3>Supprimer cet utilisateur ?</h3><p><strong>{deleteCandidate.full_name}</strong> · {deleteCandidate.phone}<br />La ligne sera supprimée définitivement de <code>public.users</code>.</p><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setDeleteCandidate(null)}>Annuler</button><button type="button" className="button danger-button" onClick={() => void confirmDelete()} disabled={actionLoading}>{actionLoading ? <LoaderCircle className="spin" size={14} /> : <Trash2 size={14} />} Confirmer</button></div></div></div>}
  </section>;
}
export default AdminDashboard;
